[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = true
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Waline"
  LiveReId = "my-waline"
  WalineSerURL = "https://my-waline-3mkfqkj6h-itvita.vercel.app"

[LeanCloud]
  AppId = "nGRVvdAmPr0I0HJHSFtS3lLq-MdYXbMMI"
  AppKey = "6YeetGiOhNRu9FEV1Sk63sFG"
  ServerURL = "waline.itvita.cn"

[Statis]
  BusuanziCounter = true
#  CNNZSiteId = "Your CNNZSiteId"
  BaiduSiteId = "f43be215263abb41e413517e0bce18e8"
#  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = true
  DaoVoiceId = "33dc1ab1"

[Others]
  RevolverMapId = "5vcdkhaq1g6"
