Description = "欢迎来到IT生活小宅，个人主要专注于全栈开发技术。"
Keywords =  "博客, 程序员, 架构师, 思考, 读书, 笔记, 技术, 分享, 全栈, 产品, 前端, 后端"
Subtitle = "没有伞的孩子要学会努力奔跑!"
AuthorImg = "/img/avatar.jpg"
AuthorName = "itvita"
Introduce = "再平凡的人也有属于他自己的梦想!"
DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"

[Footer]
  ICPLink = "http://beian.miit.gov.cn"
  ICPNo = "豫ICP备2020032888号-1"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/itvita"

[[Socials]]
  Name = "gitee"
  Icon = "git"
  URL = "https://gitee.com/itvita"

[[Links]]
  Name = "itvita"
  Permalink = "https://itvita.cn"
